# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './GUI/Design.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1205, 926)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(9, 9, 1187, 651))
        self.tabWidget.setObjectName("tabWidget")
        self.Calibrate_System = QtWidgets.QWidget()
        self.Calibrate_System.setObjectName("Calibrate_System")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.Calibrate_System)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.change_working_directory = QtWidgets.QPushButton(self.Calibrate_System)
        self.change_working_directory.setObjectName("change_working_directory")
        self.gridLayout_3.addWidget(self.change_working_directory, 0, 3, 1, 1)
        self.use_taken_photos_test = QtWidgets.QRadioButton(self.Calibrate_System)
        self.use_taken_photos_test.setAutoExclusive(False)
        self.use_taken_photos_test.setObjectName("use_taken_photos_test")
        self.gridLayout_3.addWidget(self.use_taken_photos_test, 13, 8, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.Calibrate_System)
        self.label_31.setObjectName("label_31")
        self.gridLayout_3.addWidget(self.label_31, 13, 3, 1, 1)
        self.cam_R_idx = QtWidgets.QSpinBox(self.Calibrate_System)
        self.cam_R_idx.setMinimum(0)
        self.cam_R_idx.setProperty("value", 1)
        self.cam_R_idx.setObjectName("cam_R_idx")
        self.gridLayout_3.addWidget(self.cam_R_idx, 13, 5, 1, 1)
        self.use_taken_photos = QtWidgets.QRadioButton(self.Calibrate_System)
        self.use_taken_photos.setChecked(True)
        self.use_taken_photos.setAutoRepeat(False)
        self.use_taken_photos.setAutoExclusive(True)
        self.use_taken_photos.setObjectName("use_taken_photos")
        self.buttonGroup_2 = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup_2.setObjectName("buttonGroup_2")
        self.buttonGroup_2.addButton(self.use_taken_photos)
        self.gridLayout_3.addWidget(self.use_taken_photos, 11, 8, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.Calibrate_System)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 3, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.Calibrate_System)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 2, 0, 1, 1)
        self.chess_square_side = QtWidgets.QLineEdit(self.Calibrate_System)
        self.chess_square_side.setEnabled(True)
        self.chess_square_side.setObjectName("chess_square_side")
        self.gridLayout_3.addWidget(self.chess_square_side, 10, 3, 1, 1)
        self.progressBar_Calibrate = QtWidgets.QProgressBar(self.Calibrate_System)
        self.progressBar_Calibrate.setProperty("value", 0)
        self.progressBar_Calibrate.setTextVisible(True)
        self.progressBar_Calibrate.setObjectName("progressBar_Calibrate")
        self.gridLayout_3.addWidget(self.progressBar_Calibrate, 17, 8, 1, 1)
        self.num_photos_calibration = QtWidgets.QSpinBox(self.Calibrate_System)
        self.num_photos_calibration.setMinimum(1)
        self.num_photos_calibration.setMaximum(150)
        self.num_photos_calibration.setProperty("value", 40)
        self.num_photos_calibration.setObjectName("num_photos_calibration")
        self.gridLayout_3.addWidget(self.num_photos_calibration, 1, 3, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.Calibrate_System)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 1, 0, 1, 2)
        self.chess_size_x = QtWidgets.QSpinBox(self.Calibrate_System)
        self.chess_size_x.setMinimum(1)
        self.chess_size_x.setProperty("value", 9)
        self.chess_size_x.setObjectName("chess_size_x")
        self.gridLayout_3.addWidget(self.chess_size_x, 8, 3, 1, 1)
        self.label = QtWidgets.QLabel(self.Calibrate_System)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 3)
        self.label_5 = QtWidgets.QLabel(self.Calibrate_System)
        self.label_5.setEnabled(True)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 6, 0, 1, 1)
        self.allow_choosing = QtWidgets.QRadioButton(self.Calibrate_System)
        self.allow_choosing.setObjectName("allow_choosing")
        self.buttonGroup = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.allow_choosing)
        self.gridLayout_3.addWidget(self.allow_choosing, 3, 3, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.Calibrate_System)
        self.label_25.setObjectName("label_25")
        self.gridLayout_3.addWidget(self.label_25, 10, 0, 1, 1)
        self.working_directory = QtWidgets.QLineEdit(self.Calibrate_System)
        self.working_directory.setObjectName("working_directory")
        self.gridLayout_3.addWidget(self.working_directory, 0, 4, 1, 5)
        self.previs_ms = QtWidgets.QLineEdit(self.Calibrate_System)
        self.previs_ms.setEnabled(True)
        self.previs_ms.setObjectName("previs_ms")
        self.gridLayout_3.addWidget(self.previs_ms, 6, 3, 1, 1)
        self.num_photos_test = QtWidgets.QSpinBox(self.Calibrate_System)
        self.num_photos_test.setMinimum(1)
        self.num_photos_test.setProperty("value", 20)
        self.num_photos_test.setDisplayIntegerBase(10)
        self.num_photos_test.setObjectName("num_photos_test")
        self.gridLayout_3.addWidget(self.num_photos_test, 2, 3, 1, 1)
        self.radioButton_2 = QtWidgets.QRadioButton(self.Calibrate_System)
        self.radioButton_2.setEnabled(True)
        self.radioButton_2.setChecked(True)
        self.radioButton_2.setObjectName("radioButton_2")
        self.buttonGroup.addButton(self.radioButton_2)
        self.gridLayout_3.addWidget(self.radioButton_2, 5, 3, 1, 1)
        self.start_calibration = QtWidgets.QPushButton(self.Calibrate_System)
        self.start_calibration.setAutoFillBackground(False)
        self.start_calibration.setObjectName("start_calibration")
        self.gridLayout_3.addWidget(self.start_calibration, 17, 1, 1, 6)
        self.label_17 = QtWidgets.QLabel(self.Calibrate_System)
        self.label_17.setObjectName("label_17")
        self.gridLayout_3.addWidget(self.label_17, 8, 0, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.Calibrate_System)
        self.label_24.setObjectName("label_24")
        self.gridLayout_3.addWidget(self.label_24, 8, 4, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.Calibrate_System)
        self.label_30.setObjectName("label_30")
        self.gridLayout_3.addWidget(self.label_30, 11, 3, 1, 1)
        self.chess_size_y = QtWidgets.QSpinBox(self.Calibrate_System)
        self.chess_size_y.setMinimum(1)
        self.chess_size_y.setProperty("value", 6)
        self.chess_size_y.setObjectName("chess_size_y")
        self.gridLayout_3.addWidget(self.chess_size_y, 8, 5, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.Calibrate_System)
        self.label_29.setObjectName("label_29")
        self.gridLayout_3.addWidget(self.label_29, 11, 0, 1, 1)
        self.remove_old_data = QtWidgets.QRadioButton(self.Calibrate_System)
        self.remove_old_data.setChecked(False)
        self.remove_old_data.setAutoRepeat(False)
        self.remove_old_data.setAutoExclusive(True)
        self.remove_old_data.setObjectName("remove_old_data")
        self.buttonGroup_2.addButton(self.remove_old_data)
        self.gridLayout_3.addWidget(self.remove_old_data, 14, 8, 1, 1)
        self.cam_L_idx = QtWidgets.QSpinBox(self.Calibrate_System)
        self.cam_L_idx.setMinimum(0)
        self.cam_L_idx.setProperty("value", 2)
        self.cam_L_idx.setObjectName("cam_L_idx")
        self.gridLayout_3.addWidget(self.cam_L_idx, 11, 5, 1, 1)
        self.tabWidget_2 = QtWidgets.QTabWidget(self.Calibrate_System)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.camera_criteria_eps = QtWidgets.QLineEdit(self.tab)
        self.camera_criteria_eps.setObjectName("camera_criteria_eps")
        self.gridLayout_4.addWidget(self.camera_criteria_eps, 2, 1, 1, 1)
        self.corner_criteria_its = QtWidgets.QLineEdit(self.tab)
        self.corner_criteria_its.setObjectName("corner_criteria_its")
        self.gridLayout_4.addWidget(self.corner_criteria_its, 1, 2, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.tab)
        self.label_26.setObjectName("label_26")
        self.gridLayout_4.addWidget(self.label_26, 1, 0, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.tab)
        self.label_28.setObjectName("label_28")
        self.gridLayout_4.addWidget(self.label_28, 0, 1, 1, 1)
        self.stereocalib_criteria_its = QtWidgets.QLineEdit(self.tab)
        self.stereocalib_criteria_its.setObjectName("stereocalib_criteria_its")
        self.gridLayout_4.addWidget(self.stereocalib_criteria_its, 3, 2, 1, 1)
        self.stereocalib_criteria_eps = QtWidgets.QLineEdit(self.tab)
        self.stereocalib_criteria_eps.setObjectName("stereocalib_criteria_eps")
        self.gridLayout_4.addWidget(self.stereocalib_criteria_eps, 3, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setObjectName("label_6")
        self.gridLayout_4.addWidget(self.label_6, 2, 0, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.tab)
        self.label_27.setObjectName("label_27")
        self.gridLayout_4.addWidget(self.label_27, 0, 2, 1, 1)
        self.corner_criteria_eps = QtWidgets.QLineEdit(self.tab)
        self.corner_criteria_eps.setObjectName("corner_criteria_eps")
        self.gridLayout_4.addWidget(self.corner_criteria_eps, 1, 1, 1, 1)
        self.camera_criteria_its = QtWidgets.QLineEdit(self.tab)
        self.camera_criteria_its.setObjectName("camera_criteria_its")
        self.gridLayout_4.addWidget(self.camera_criteria_its, 2, 2, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.tab)
        self.label_9.setObjectName("label_9")
        self.gridLayout_4.addWidget(self.label_9, 3, 0, 1, 1)
        self.tabWidget_2.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.CALIB_FIX_INTRINSIC = QtWidgets.QRadioButton(self.tab_2)
        self.CALIB_FIX_INTRINSIC.setAutoExclusive(False)
        self.CALIB_FIX_INTRINSIC.setObjectName("CALIB_FIX_INTRINSIC")
        self.gridLayout_5.addWidget(self.CALIB_FIX_INTRINSIC, 0, 0, 1, 1)
        self.CALIB_FIX_K1 = QtWidgets.QRadioButton(self.tab_2)
        self.CALIB_FIX_K1.setAutoExclusive(False)
        self.CALIB_FIX_K1.setObjectName("CALIB_FIX_K1")
        self.gridLayout_5.addWidget(self.CALIB_FIX_K1, 0, 1, 1, 1)
        self.CALIB_FIX_PRINCIPAL_POINT = QtWidgets.QRadioButton(self.tab_2)
        self.CALIB_FIX_PRINCIPAL_POINT.setAutoExclusive(False)
        self.CALIB_FIX_PRINCIPAL_POINT.setObjectName("CALIB_FIX_PRINCIPAL_POINT")
        self.gridLayout_5.addWidget(self.CALIB_FIX_PRINCIPAL_POINT, 1, 0, 1, 1)
        self.CALIB_FIX_K2 = QtWidgets.QRadioButton(self.tab_2)
        self.CALIB_FIX_K2.setAutoExclusive(False)
        self.CALIB_FIX_K2.setObjectName("CALIB_FIX_K2")
        self.gridLayout_5.addWidget(self.CALIB_FIX_K2, 1, 1, 1, 1)
        self.CALIB_FIX_FOCAL_LENGTH = QtWidgets.QRadioButton(self.tab_2)
        self.CALIB_FIX_FOCAL_LENGTH.setChecked(False)
        self.CALIB_FIX_FOCAL_LENGTH.setAutoRepeat(False)
        self.CALIB_FIX_FOCAL_LENGTH.setAutoExclusive(False)
        self.CALIB_FIX_FOCAL_LENGTH.setObjectName("CALIB_FIX_FOCAL_LENGTH")
        self.gridLayout_5.addWidget(self.CALIB_FIX_FOCAL_LENGTH, 2, 0, 1, 1)
        self.CALIB_FIX_K3 = QtWidgets.QRadioButton(self.tab_2)
        self.CALIB_FIX_K3.setAutoExclusive(False)
        self.CALIB_FIX_K3.setObjectName("CALIB_FIX_K3")
        self.gridLayout_5.addWidget(self.CALIB_FIX_K3, 2, 1, 1, 1)
        self.CALIB_FIX_ASPECT_RATIO = QtWidgets.QRadioButton(self.tab_2)
        self.CALIB_FIX_ASPECT_RATIO.setChecked(False)
        self.CALIB_FIX_ASPECT_RATIO.setAutoExclusive(False)
        self.CALIB_FIX_ASPECT_RATIO.setObjectName("CALIB_FIX_ASPECT_RATIO")
        self.gridLayout_5.addWidget(self.CALIB_FIX_ASPECT_RATIO, 3, 0, 1, 1)
        self.CALIB_FIX_K4 = QtWidgets.QRadioButton(self.tab_2)
        self.CALIB_FIX_K4.setAutoExclusive(False)
        self.CALIB_FIX_K4.setObjectName("CALIB_FIX_K4")
        self.gridLayout_5.addWidget(self.CALIB_FIX_K4, 3, 1, 1, 1)
        self.CALIB_SAME_FOCAL_LENGTH = QtWidgets.QRadioButton(self.tab_2)
        self.CALIB_SAME_FOCAL_LENGTH.setAutoExclusive(False)
        self.CALIB_SAME_FOCAL_LENGTH.setObjectName("CALIB_SAME_FOCAL_LENGTH")
        self.gridLayout_5.addWidget(self.CALIB_SAME_FOCAL_LENGTH, 4, 0, 1, 1)
        self.CALIB_FIX_K5 = QtWidgets.QRadioButton(self.tab_2)
        self.CALIB_FIX_K5.setAutoExclusive(False)
        self.CALIB_FIX_K5.setObjectName("CALIB_FIX_K5")
        self.gridLayout_5.addWidget(self.CALIB_FIX_K5, 4, 1, 1, 1)
        self.CALIB_ZERO_TANGENT_DIST = QtWidgets.QRadioButton(self.tab_2)
        self.CALIB_ZERO_TANGENT_DIST.setAutoExclusive(False)
        self.CALIB_ZERO_TANGENT_DIST.setObjectName("CALIB_ZERO_TANGENT_DIST")
        self.gridLayout_5.addWidget(self.CALIB_ZERO_TANGENT_DIST, 5, 0, 1, 1)
        self.CALIB_FIX_K6 = QtWidgets.QRadioButton(self.tab_2)
        self.CALIB_FIX_K6.setAutoExclusive(False)
        self.CALIB_FIX_K6.setObjectName("CALIB_FIX_K6")
        self.gridLayout_5.addWidget(self.CALIB_FIX_K6, 5, 1, 1, 1)
        self.CALIB_USE_INTRINSIC_GUESS = QtWidgets.QRadioButton(self.tab_2)
        self.CALIB_USE_INTRINSIC_GUESS.setChecked(True)
        self.CALIB_USE_INTRINSIC_GUESS.setAutoExclusive(False)
        self.CALIB_USE_INTRINSIC_GUESS.setObjectName("CALIB_USE_INTRINSIC_GUESS")
        self.gridLayout_5.addWidget(self.CALIB_USE_INTRINSIC_GUESS, 6, 0, 1, 2)
        self.tabWidget_2.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.CALIB_ZERO_DISPARITY = QtWidgets.QRadioButton(self.tab_3)
        self.CALIB_ZERO_DISPARITY.setChecked(True)
        self.CALIB_ZERO_DISPARITY.setObjectName("CALIB_ZERO_DISPARITY")
        self.gridLayout_6.addWidget(self.CALIB_ZERO_DISPARITY, 0, 0, 1, 2)
        self.label_10 = QtWidgets.QLabel(self.tab_3)
        self.label_10.setObjectName("label_10")
        self.gridLayout_6.addWidget(self.label_10, 1, 0, 1, 1)
        self.alpha = QtWidgets.QLineEdit(self.tab_3)
        self.alpha.setObjectName("alpha")
        self.gridLayout_6.addWidget(self.alpha, 1, 1, 1, 1)
        self.tabWidget_2.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.tab_4)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_11 = QtWidgets.QLabel(self.tab_4)
        self.label_11.setObjectName("label_11")
        self.gridLayout_7.addWidget(self.label_11, 0, 0, 2, 1)
        self.block_size = QtWidgets.QLineEdit(self.tab_4)
        self.block_size.setObjectName("block_size")
        self.gridLayout_7.addWidget(self.block_size, 0, 1, 1, 2)
        self.label_12 = QtWidgets.QLabel(self.tab_4)
        self.label_12.setObjectName("label_12")
        self.gridLayout_7.addWidget(self.label_12, 2, 0, 1, 1)
        self.min_disp = QtWidgets.QLineEdit(self.tab_4)
        self.min_disp.setObjectName("min_disp")
        self.gridLayout_7.addWidget(self.min_disp, 2, 1, 1, 2)
        self.label_14 = QtWidgets.QLabel(self.tab_4)
        self.label_14.setObjectName("label_14")
        self.gridLayout_7.addWidget(self.label_14, 3, 0, 1, 1)
        self.num_disp = QtWidgets.QLineEdit(self.tab_4)
        self.num_disp.setObjectName("num_disp")
        self.gridLayout_7.addWidget(self.num_disp, 3, 2, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.tab_4)
        self.label_15.setObjectName("label_15")
        self.gridLayout_7.addWidget(self.label_15, 4, 0, 1, 1)
        self.uniquenessRatio = QtWidgets.QLineEdit(self.tab_4)
        self.uniquenessRatio.setObjectName("uniquenessRatio")
        self.gridLayout_7.addWidget(self.uniquenessRatio, 4, 2, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.tab_4)
        self.label_16.setObjectName("label_16")
        self.gridLayout_7.addWidget(self.label_16, 5, 0, 1, 1)
        self.speckleWindowSize = QtWidgets.QLineEdit(self.tab_4)
        self.speckleWindowSize.setObjectName("speckleWindowSize")
        self.gridLayout_7.addWidget(self.speckleWindowSize, 5, 2, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.tab_4)
        self.label_18.setObjectName("label_18")
        self.gridLayout_7.addWidget(self.label_18, 0, 3, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.tab_4)
        self.label_19.setObjectName("label_19")
        self.gridLayout_7.addWidget(self.label_19, 2, 3, 1, 1)
        self.speckleRange = QtWidgets.QLineEdit(self.tab_4)
        self.speckleRange.setObjectName("speckleRange")
        self.gridLayout_7.addWidget(self.speckleRange, 0, 5, 1, 1)
        self.disp12MaxDiff = QtWidgets.QLineEdit(self.tab_4)
        self.disp12MaxDiff.setObjectName("disp12MaxDiff")
        self.gridLayout_7.addWidget(self.disp12MaxDiff, 2, 5, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.tab_4)
        self.label_21.setObjectName("label_21")
        self.gridLayout_7.addWidget(self.label_21, 4, 3, 1, 1)
        self.lmbda = QtWidgets.QLineEdit(self.tab_4)
        self.lmbda.setObjectName("lmbda")
        self.gridLayout_7.addWidget(self.lmbda, 4, 5, 1, 1)
        self.sigma = QtWidgets.QLineEdit(self.tab_4)
        self.sigma.setObjectName("sigma")
        self.gridLayout_7.addWidget(self.sigma, 5, 5, 1, 1)
        self.visual_multiplier = QtWidgets.QLineEdit(self.tab_4)
        self.visual_multiplier.setObjectName("visual_multiplier")
        self.gridLayout_7.addWidget(self.visual_multiplier, 6, 5, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.tab_4)
        self.label_22.setObjectName("label_22")
        self.gridLayout_7.addWidget(self.label_22, 5, 3, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.tab_4)
        self.label_23.setObjectName("label_23")
        self.gridLayout_7.addWidget(self.label_23, 6, 3, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.tab_4)
        self.label_20.setObjectName("label_20")
        self.gridLayout_7.addWidget(self.label_20, 3, 5, 1, 1)
        self.tabWidget_2.addTab(self.tab_4, "")
        self.gridLayout_3.addWidget(self.tabWidget_2, 1, 7, 10, 2)
        self.tabWidget.addTab(self.Calibrate_System, "")
        self.Generate_Depth_Maps = QtWidgets.QWidget()
        self.Generate_Depth_Maps.setObjectName("Generate_Depth_Maps")
        self.stereo_calibrate_param_path = QtWidgets.QLineEdit(self.Generate_Depth_Maps)
        self.stereo_calibrate_param_path.setGeometry(QtCore.QRect(400, 50, 581, 41))
        self.stereo_calibrate_param_path.setObjectName("stereo_calibrate_param_path")
        self.label_7 = QtWidgets.QLabel(self.Generate_Depth_Maps)
        self.label_7.setGeometry(QtCore.QRect(30, 50, 361, 41))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.Generate_Depth_Maps)
        self.label_8.setGeometry(QtCore.QRect(30, 10, 261, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.change_stereo_calib_path = QtWidgets.QPushButton(self.Generate_Depth_Maps)
        self.change_stereo_calib_path.setGeometry(QtCore.QRect(1020, 50, 108, 34))
        self.change_stereo_calib_path.setObjectName("change_stereo_calib_path")
        self.stereo_rectify_param_path = QtWidgets.QLineEdit(self.Generate_Depth_Maps)
        self.stereo_rectify_param_path.setGeometry(QtCore.QRect(400, 120, 581, 41))
        self.stereo_rectify_param_path.setText("")
        self.stereo_rectify_param_path.setObjectName("stereo_rectify_param_path")
        self.label_13 = QtWidgets.QLabel(self.Generate_Depth_Maps)
        self.label_13.setGeometry(QtCore.QRect(30, 120, 361, 41))
        self.label_13.setObjectName("label_13")
        self.change_stereo_rectify_path = QtWidgets.QPushButton(self.Generate_Depth_Maps)
        self.change_stereo_rectify_path.setGeometry(QtCore.QRect(1020, 120, 108, 34))
        self.change_stereo_rectify_path.setObjectName("change_stereo_rectify_path")
        self.save_taken_sequence = QtWidgets.QRadioButton(self.Generate_Depth_Maps)
        self.save_taken_sequence.setGeometry(QtCore.QRect(50, 260, 231, 31))
        self.save_taken_sequence.setChecked(True)
        self.save_taken_sequence.setAutoExclusive(False)
        self.save_taken_sequence.setObjectName("save_taken_sequence")
        self.label_32 = QtWidgets.QLabel(self.Generate_Depth_Maps)
        self.label_32.setEnabled(True)
        self.label_32.setGeometry(QtCore.QRect(51, 322, 291, 51))
        self.label_32.setObjectName("label_32")
        self.time_between_frames = QtWidgets.QLineEdit(self.Generate_Depth_Maps)
        self.time_between_frames.setEnabled(True)
        self.time_between_frames.setGeometry(QtCore.QRect(360, 330, 155, 34))
        self.time_between_frames.setObjectName("time_between_frames")
        self.label_33 = QtWidgets.QLabel(self.Generate_Depth_Maps)
        self.label_33.setGeometry(QtCore.QRect(30, 200, 261, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_33.setFont(font)
        self.label_33.setObjectName("label_33")
        self.show_life_frames = QtWidgets.QRadioButton(self.Generate_Depth_Maps)
        self.show_life_frames.setGeometry(QtCore.QRect(630, 260, 381, 31))
        self.show_life_frames.setChecked(True)
        self.show_life_frames.setAutoExclusive(False)
        self.show_life_frames.setObjectName("show_life_frames")
        self.frame_number = QtWidgets.QLineEdit(self.Generate_Depth_Maps)
        self.frame_number.setEnabled(True)
        self.frame_number.setGeometry(QtCore.QRect(359, 408, 155, 34))
        self.frame_number.setObjectName("frame_number")
        self.label_34 = QtWidgets.QLabel(self.Generate_Depth_Maps)
        self.label_34.setEnabled(True)
        self.label_34.setGeometry(QtCore.QRect(50, 400, 291, 51))
        self.label_34.setObjectName("label_34")
        self.start_take = QtWidgets.QPushButton(self.Generate_Depth_Maps)
        self.start_take.setGeometry(QtCore.QRect(248, 500, 260, 34))
        self.start_take.setAutoFillBackground(False)
        self.start_take.setObjectName("start_take")
        self.progressBar_Life = QtWidgets.QProgressBar(self.Generate_Depth_Maps)
        self.progressBar_Life.setGeometry(QtCore.QRect(520, 500, 656, 34))
        self.progressBar_Life.setProperty("value", 0)
        self.progressBar_Life.setTextVisible(True)
        self.progressBar_Life.setObjectName("progressBar_Life")
        self.remove_old_data_life = QtWidgets.QRadioButton(self.Generate_Depth_Maps)
        self.remove_old_data_life.setGeometry(QtCore.QRect(630, 320, 641, 32))
        self.remove_old_data_life.setChecked(False)
        self.remove_old_data_life.setAutoRepeat(False)
        self.remove_old_data_life.setAutoExclusive(True)
        self.remove_old_data_life.setObjectName("remove_old_data_life")
        self.use_taken_photos_life = QtWidgets.QRadioButton(self.Generate_Depth_Maps)
        self.use_taken_photos_life.setGeometry(QtCore.QRect(630, 390, 656, 32))
        self.use_taken_photos_life.setChecked(True)
        self.use_taken_photos_life.setAutoExclusive(True)
        self.use_taken_photos_life.setObjectName("use_taken_photos_life")
        self.label_35 = QtWidgets.QLabel(self.Generate_Depth_Maps)
        self.label_35.setGeometry(QtCore.QRect(120, 560, 761, 31))
        self.label_35.setObjectName("label_35")
        self.tabWidget.addTab(self.Generate_Depth_Maps, "")
        self.log_text = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.log_text.setGeometry(QtCore.QRect(10, 670, 1181, 191))
        self.log_text.setReadOnly(True)
        self.log_text.setObjectName("log_text")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1205, 31))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        self.tabWidget_2.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Depth Map Generator using Stero Imaging"))
        self.change_working_directory.setText(_translate("MainWindow", "Change"))
        self.use_taken_photos_test.setText(_translate("MainWindow", "Use already taken photos for testing"))
        self.label_31.setText(_translate("MainWindow", "Right:"))
        self.use_taken_photos.setText(_translate("MainWindow", "Use already taken photos in the Working Directory"))
        self.label_4.setText(_translate("MainWindow", "- Take all the correct\n"
"images or allow choosing?"))
        self.label_3.setText(_translate("MainWindow", "- Number of Photos to take \n"
" for Test:"))
        self.chess_square_side.setText(_translate("MainWindow", "2.4"))
        self.label_2.setText(_translate("MainWindow", "- Number of Photosto take \n"
"in Calibration:"))
        self.label.setText(_translate("MainWindow", "- Working Directory:"))
        self.label_5.setText(_translate("MainWindow", "- If All Taken, timing (ms) of \n"
"previsualization"))
        self.allow_choosing.setText(_translate("MainWindow", "Allow Choosing"))
        self.label_25.setText(_translate("MainWindow", "- Chess square side\n"
" (you will fix the units):"))
        self.previs_ms.setText(_translate("MainWindow", "150"))
        self.radioButton_2.setText(_translate("MainWindow", "Take All"))
        self.start_calibration.setText(_translate("MainWindow", "START CALIBRATION"))
        self.label_17.setText(_translate("MainWindow", "- Chess size:"))
        self.label_24.setText(_translate("MainWindow", "x"))
        self.label_30.setText(_translate("MainWindow", "Left:"))
        self.label_29.setText(_translate("MainWindow", "- Camera Indices:"))
        self.remove_old_data.setText(_translate("MainWindow", "Remove old Data"))
        self.camera_criteria_eps.setText(_translate("MainWindow", "1e-5"))
        self.corner_criteria_its.setText(_translate("MainWindow", "1000"))
        self.label_26.setText(_translate("MainWindow", "Chess\n"
"Corner\n"
"Detection:"))
        self.label_28.setText(_translate("MainWindow", "Epsilon"))
        self.stereocalib_criteria_its.setText(_translate("MainWindow", "1000"))
        self.stereocalib_criteria_eps.setText(_translate("MainWindow", "1e-5"))
        self.label_6.setText(_translate("MainWindow", "Calibrate \n"
"Each Camera"))
        self.label_27.setText(_translate("MainWindow", "Max. Iterations"))
        self.corner_criteria_eps.setText(_translate("MainWindow", "1e-5"))
        self.camera_criteria_its.setText(_translate("MainWindow", "1000"))
        self.label_9.setText(_translate("MainWindow", "Stereo \n"
"Calibration:"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab), _translate("MainWindow", "Opt. Stop Crit."))
        self.CALIB_FIX_INTRINSIC.setText(_translate("MainWindow", "CALIB_FIX_INTRINSIC"))
        self.CALIB_FIX_K1.setText(_translate("MainWindow", "CALIB_FIX_K1"))
        self.CALIB_FIX_PRINCIPAL_POINT.setText(_translate("MainWindow", "CALIB_FIX_PRINCIPAL_POINT"))
        self.CALIB_FIX_K2.setText(_translate("MainWindow", "CALIB_FIX_K2"))
        self.CALIB_FIX_FOCAL_LENGTH.setText(_translate("MainWindow", "CALIB_FIX_FOCAL_LENGTH"))
        self.CALIB_FIX_K3.setText(_translate("MainWindow", "CALIB_FIX_K3"))
        self.CALIB_FIX_ASPECT_RATIO.setText(_translate("MainWindow", "CALIB_FIX_ASPECT_RATIO"))
        self.CALIB_FIX_K4.setText(_translate("MainWindow", "CALIB_FIX_K4"))
        self.CALIB_SAME_FOCAL_LENGTH.setText(_translate("MainWindow", "CALIB_SAME_FOCAL_LENGTH"))
        self.CALIB_FIX_K5.setText(_translate("MainWindow", "CALIB_FIX_K5"))
        self.CALIB_ZERO_TANGENT_DIST.setText(_translate("MainWindow", "CALIB_ZERO_TANGENT_DIST"))
        self.CALIB_FIX_K6.setText(_translate("MainWindow", "CALIB_FIX_K6"))
        self.CALIB_USE_INTRINSIC_GUESS.setText(_translate("MainWindow", "CALIB_USE_INTRINSIC_GUESS"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_2), _translate("MainWindow", "StereoCalibrate"))
        self.CALIB_ZERO_DISPARITY.setText(_translate("MainWindow", "CALIB_ZERO_DISPARITY"))
        self.label_10.setText(_translate("MainWindow", "Alpha:"))
        self.alpha.setText(_translate("MainWindow", "1"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), _translate("MainWindow", "StereoRectify"))
        self.label_11.setText(_translate("MainWindow", "Block Size (3-11):"))
        self.block_size.setText(_translate("MainWindow", "15"))
        self.label_12.setText(_translate("MainWindow", "Min Disparity:"))
        self.min_disp.setText(_translate("MainWindow", "0"))
        self.label_14.setText(_translate("MainWindow", "Num Disparities:\n"
"(max-min should \n"
"be divsble by 16)"))
        self.num_disp.setText(_translate("MainWindow", "64"))
        self.label_15.setText(_translate("MainWindow", "Uniqueness Ratio \n"
"(5-15):"))
        self.uniquenessRatio.setText(_translate("MainWindow", "10"))
        self.label_16.setText(_translate("MainWindow", "Speckle Window\n"
" Size (50-200):"))
        self.speckleWindowSize.setText(_translate("MainWindow", "200"))
        self.label_18.setText(_translate("MainWindow", "Speckle Range (1-2):"))
        self.label_19.setText(_translate("MainWindow", "Disp12MaxDiff:"))
        self.speckleRange.setText(_translate("MainWindow", "2"))
        self.disp12MaxDiff.setText(_translate("MainWindow", "0"))
        self.label_21.setText(_translate("MainWindow", "Lambda:"))
        self.lmbda.setText(_translate("MainWindow", "8000"))
        self.sigma.setText(_translate("MainWindow", "2.0"))
        self.visual_multiplier.setText(_translate("MainWindow", "6"))
        self.label_22.setText(_translate("MainWindow", "Sigma:"))
        self.label_23.setText(_translate("MainWindow", "Visual Multiplier:"))
        self.label_20.setText(_translate("MainWindow", "FILTER parameters:"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), _translate("MainWindow", "Disparity SGBM"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Calibrate_System), _translate("MainWindow", "Calibrate System"))
        self.label_7.setText(_translate("MainWindow", "- Stereo Calibrate Calibrated Parameters:"))
        self.label_8.setText(_translate("MainWindow", "Import calibrated Parameters"))
        self.change_stereo_calib_path.setText(_translate("MainWindow", "Change"))
        self.label_13.setText(_translate("MainWindow", "- Stereo Rectify Calibrated Parameters:"))
        self.change_stereo_rectify_path.setText(_translate("MainWindow", "Change"))
        self.save_taken_sequence.setText(_translate("MainWindow", "Save Taken Sequence"))
        self.label_32.setText(_translate("MainWindow", "- Time between taken frames (ms)"))
        self.time_between_frames.setText(_translate("MainWindow", "1000"))
        self.label_33.setText(_translate("MainWindow", "Parameters for life takes"))
        self.show_life_frames.setText(_translate("MainWindow", "Show frames while taking sequence"))
        self.frame_number.setText(_translate("MainWindow", "30"))
        self.label_34.setText(_translate("MainWindow", "- Number of Frames to Take"))
        self.start_take.setText(_translate("MainWindow", "GO"))
        self.remove_old_data_life.setText(_translate("MainWindow", "Remove old data from Takes"))
        self.use_taken_photos_life.setText(_translate("MainWindow", "Use already taken photos "))
        self.label_35.setText(_translate("MainWindow", "Remember to choose the Disparity SGMB paramteres and cameras in the other Tab!"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Generate_Depth_Maps), _translate("MainWindow", "Generate Depth Maps"))
        self.log_text.setPlainText(_translate("MainWindow", "Click Start Calibration to begin calibration process, or Click GO to start generating depth maps...\n"
""))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

