# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Design.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(812, 693)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 811, 651))
        self.tabWidget.setObjectName("tabWidget")
        self.Calibrate_System = QtWidgets.QWidget()
        self.Calibrate_System.setObjectName("Calibrate_System")
        self.working_directory = QtWidgets.QLineEdit(self.Calibrate_System)
        self.working_directory.setGeometry(QtCore.QRect(160, 10, 401, 21))
        self.working_directory.setObjectName("working_directory")
        self.label = QtWidgets.QLabel(self.Calibrate_System)
        self.label.setGeometry(QtCore.QRect(20, 10, 161, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.Calibrate_System)
        self.label_2.setGeometry(QtCore.QRect(20, 30, 131, 61))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.Calibrate_System)
        self.label_3.setGeometry(QtCore.QRect(20, 70, 131, 61))
        self.label_3.setObjectName("label_3")
        self.num_photos_test = QtWidgets.QSpinBox(self.Calibrate_System)
        self.num_photos_test.setGeometry(QtCore.QRect(180, 90, 47, 24))
        self.num_photos_test.setMinimum(1)
        self.num_photos_test.setProperty("value", 15)
        self.num_photos_test.setDisplayIntegerBase(10)
        self.num_photos_test.setObjectName("num_photos_test")
        self.num_photos_calibration = QtWidgets.QSpinBox(self.Calibrate_System)
        self.num_photos_calibration.setGeometry(QtCore.QRect(180, 50, 47, 24))
        self.num_photos_calibration.setMinimum(1)
        self.num_photos_calibration.setProperty("value", 20)
        self.num_photos_calibration.setObjectName("num_photos_calibration")
        self.label_4 = QtWidgets.QLabel(self.Calibrate_System)
        self.label_4.setGeometry(QtCore.QRect(20, 130, 161, 51))
        self.label_4.setObjectName("label_4")
        self.allow_choosing = QtWidgets.QRadioButton(self.Calibrate_System)
        self.allow_choosing.setGeometry(QtCore.QRect(190, 130, 121, 21))
        self.allow_choosing.setObjectName("allow_choosing")
        self.buttonGroup = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.allow_choosing)
        self.radioButton_2 = QtWidgets.QRadioButton(self.Calibrate_System)
        self.radioButton_2.setEnabled(True)
        self.radioButton_2.setGeometry(QtCore.QRect(190, 160, 100, 21))
        self.radioButton_2.setChecked(True)
        self.radioButton_2.setObjectName("radioButton_2")
        self.buttonGroup.addButton(self.radioButton_2)
        self.label_5 = QtWidgets.QLabel(self.Calibrate_System)
        self.label_5.setEnabled(True)
        self.label_5.setGeometry(QtCore.QRect(20, 190, 161, 51))
        self.label_5.setObjectName("label_5")
        self.previs_ms = QtWidgets.QLineEdit(self.Calibrate_System)
        self.previs_ms.setEnabled(True)
        self.previs_ms.setGeometry(QtCore.QRect(150, 200, 111, 21))
        self.previs_ms.setObjectName("previs_ms")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.Calibrate_System)
        self.tabWidget_2.setGeometry(QtCore.QRect(320, 50, 471, 291))
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setGeometry(QtCore.QRect(20, 120, 81, 31))
        self.label_6.setObjectName("label_6")
        self.camera_criteria_eps = QtWidgets.QLineEdit(self.tab)
        self.camera_criteria_eps.setGeometry(QtCore.QRect(120, 130, 91, 21))
        self.camera_criteria_eps.setObjectName("camera_criteria_eps")
        self.camera_criteria_its = QtWidgets.QLineEdit(self.tab)
        self.camera_criteria_its.setGeometry(QtCore.QRect(270, 130, 91, 21))
        self.camera_criteria_its.setObjectName("camera_criteria_its")
        self.stereocalib_criteria_eps = QtWidgets.QLineEdit(self.tab)
        self.stereocalib_criteria_eps.setGeometry(QtCore.QRect(120, 180, 91, 21))
        self.stereocalib_criteria_eps.setObjectName("stereocalib_criteria_eps")
        self.stereocalib_criteria_its = QtWidgets.QLineEdit(self.tab)
        self.stereocalib_criteria_its.setGeometry(QtCore.QRect(270, 180, 91, 21))
        self.stereocalib_criteria_its.setObjectName("stereocalib_criteria_its")
        self.label_9 = QtWidgets.QLabel(self.tab)
        self.label_9.setGeometry(QtCore.QRect(20, 170, 81, 31))
        self.label_9.setObjectName("label_9")
        self.label_26 = QtWidgets.QLabel(self.tab)
        self.label_26.setGeometry(QtCore.QRect(20, 60, 81, 41))
        self.label_26.setObjectName("label_26")
        self.corner_criteria_its = QtWidgets.QLineEdit(self.tab)
        self.corner_criteria_its.setGeometry(QtCore.QRect(270, 70, 91, 21))
        self.corner_criteria_its.setObjectName("corner_criteria_its")
        self.corner_criteria_eps = QtWidgets.QLineEdit(self.tab)
        self.corner_criteria_eps.setGeometry(QtCore.QRect(120, 70, 91, 21))
        self.corner_criteria_eps.setObjectName("corner_criteria_eps")
        self.label_27 = QtWidgets.QLabel(self.tab)
        self.label_27.setGeometry(QtCore.QRect(260, 30, 101, 16))
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.tab)
        self.label_28.setGeometry(QtCore.QRect(130, 30, 59, 15))
        self.label_28.setObjectName("label_28")
        self.tabWidget_2.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.CALIB_FIX_INTRINSIC = QtWidgets.QRadioButton(self.tab_2)
        self.CALIB_FIX_INTRINSIC.setGeometry(QtCore.QRect(10, 10, 221, 21))
        self.CALIB_FIX_INTRINSIC.setAutoExclusive(False)
        self.CALIB_FIX_INTRINSIC.setObjectName("CALIB_FIX_INTRINSIC")
        self.CALIB_FIX_PRINCIPAL_POINT = QtWidgets.QRadioButton(self.tab_2)
        self.CALIB_FIX_PRINCIPAL_POINT.setGeometry(QtCore.QRect(10, 40, 221, 21))
        self.CALIB_FIX_PRINCIPAL_POINT.setAutoExclusive(False)
        self.CALIB_FIX_PRINCIPAL_POINT.setObjectName("CALIB_FIX_PRINCIPAL_POINT")
        self.CALIB_FIX_FOCAL_LENGTH = QtWidgets.QRadioButton(self.tab_2)
        self.CALIB_FIX_FOCAL_LENGTH.setGeometry(QtCore.QRect(10, 70, 221, 21))
        self.CALIB_FIX_FOCAL_LENGTH.setChecked(False)
        self.CALIB_FIX_FOCAL_LENGTH.setAutoRepeat(False)
        self.CALIB_FIX_FOCAL_LENGTH.setAutoExclusive(False)
        self.CALIB_FIX_FOCAL_LENGTH.setObjectName("CALIB_FIX_FOCAL_LENGTH")
        self.CALIB_SAME_FOCAL_LENGTH = QtWidgets.QRadioButton(self.tab_2)
        self.CALIB_SAME_FOCAL_LENGTH.setGeometry(QtCore.QRect(10, 130, 221, 21))
        self.CALIB_SAME_FOCAL_LENGTH.setAutoExclusive(False)
        self.CALIB_SAME_FOCAL_LENGTH.setObjectName("CALIB_SAME_FOCAL_LENGTH")
        self.CALIB_ZERO_TANGENT_DIST = QtWidgets.QRadioButton(self.tab_2)
        self.CALIB_ZERO_TANGENT_DIST.setGeometry(QtCore.QRect(10, 160, 221, 21))
        self.CALIB_ZERO_TANGENT_DIST.setAutoExclusive(False)
        self.CALIB_ZERO_TANGENT_DIST.setObjectName("CALIB_ZERO_TANGENT_DIST")
        self.CALIB_FIX_ASPECT_RATIO = QtWidgets.QRadioButton(self.tab_2)
        self.CALIB_FIX_ASPECT_RATIO.setGeometry(QtCore.QRect(10, 100, 221, 21))
        self.CALIB_FIX_ASPECT_RATIO.setChecked(False)
        self.CALIB_FIX_ASPECT_RATIO.setAutoExclusive(False)
        self.CALIB_FIX_ASPECT_RATIO.setObjectName("CALIB_FIX_ASPECT_RATIO")
        self.CALIB_FIX_K5 = QtWidgets.QRadioButton(self.tab_2)
        self.CALIB_FIX_K5.setGeometry(QtCore.QRect(260, 130, 221, 21))
        self.CALIB_FIX_K5.setAutoExclusive(False)
        self.CALIB_FIX_K5.setObjectName("CALIB_FIX_K5")
        self.CALIB_FIX_K2 = QtWidgets.QRadioButton(self.tab_2)
        self.CALIB_FIX_K2.setGeometry(QtCore.QRect(260, 40, 221, 21))
        self.CALIB_FIX_K2.setAutoExclusive(False)
        self.CALIB_FIX_K2.setObjectName("CALIB_FIX_K2")
        self.CALIB_FIX_K3 = QtWidgets.QRadioButton(self.tab_2)
        self.CALIB_FIX_K3.setGeometry(QtCore.QRect(260, 70, 221, 21))
        self.CALIB_FIX_K3.setAutoExclusive(False)
        self.CALIB_FIX_K3.setObjectName("CALIB_FIX_K3")
        self.CALIB_FIX_K4 = QtWidgets.QRadioButton(self.tab_2)
        self.CALIB_FIX_K4.setGeometry(QtCore.QRect(260, 100, 221, 21))
        self.CALIB_FIX_K4.setAutoExclusive(False)
        self.CALIB_FIX_K4.setObjectName("CALIB_FIX_K4")
        self.CALIB_FIX_K1 = QtWidgets.QRadioButton(self.tab_2)
        self.CALIB_FIX_K1.setGeometry(QtCore.QRect(260, 10, 221, 21))
        self.CALIB_FIX_K1.setAutoExclusive(False)
        self.CALIB_FIX_K1.setObjectName("CALIB_FIX_K1")
        self.CALIB_FIX_K6 = QtWidgets.QRadioButton(self.tab_2)
        self.CALIB_FIX_K6.setGeometry(QtCore.QRect(260, 160, 221, 21))
        self.CALIB_FIX_K6.setAutoExclusive(False)
        self.CALIB_FIX_K6.setObjectName("CALIB_FIX_K6")
        self.CALIB_USE_INTRINSIC_GUESS = QtWidgets.QRadioButton(self.tab_2)
        self.CALIB_USE_INTRINSIC_GUESS.setGeometry(QtCore.QRect(110, 200, 221, 21))
        self.CALIB_USE_INTRINSIC_GUESS.setChecked(True)
        self.CALIB_USE_INTRINSIC_GUESS.setAutoExclusive(False)
        self.CALIB_USE_INTRINSIC_GUESS.setObjectName("CALIB_USE_INTRINSIC_GUESS")
        self.tabWidget_2.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.CALIB_ZERO_DISPARITY = QtWidgets.QRadioButton(self.tab_3)
        self.CALIB_ZERO_DISPARITY.setGeometry(QtCore.QRect(10, 20, 221, 21))
        self.CALIB_ZERO_DISPARITY.setChecked(True)
        self.CALIB_ZERO_DISPARITY.setObjectName("CALIB_ZERO_DISPARITY")
        self.label_10 = QtWidgets.QLabel(self.tab_3)
        self.label_10.setGeometry(QtCore.QRect(20, 70, 59, 15))
        self.label_10.setObjectName("label_10")
        self.alpha = QtWidgets.QLineEdit(self.tab_3)
        self.alpha.setGeometry(QtCore.QRect(70, 70, 113, 23))
        self.alpha.setObjectName("alpha")
        self.tabWidget_2.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.block_size = QtWidgets.QLineEdit(self.tab_4)
        self.block_size.setGeometry(QtCore.QRect(150, 10, 61, 23))
        self.block_size.setObjectName("block_size")
        self.label_11 = QtWidgets.QLabel(self.tab_4)
        self.label_11.setGeometry(QtCore.QRect(10, 10, 111, 16))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.tab_4)
        self.label_12.setGeometry(QtCore.QRect(10, 50, 101, 16))
        self.label_12.setObjectName("label_12")
        self.min_disp = QtWidgets.QLineEdit(self.tab_4)
        self.min_disp.setGeometry(QtCore.QRect(150, 50, 61, 23))
        self.min_disp.setObjectName("min_disp")
        self.label_13 = QtWidgets.QLabel(self.tab_4)
        self.label_13.setGeometry(QtCore.QRect(10, 90, 101, 16))
        self.label_13.setObjectName("label_13")
        self.max_disp = QtWidgets.QLineEdit(self.tab_4)
        self.max_disp.setGeometry(QtCore.QRect(150, 90, 61, 23))
        self.max_disp.setObjectName("max_disp")
        self.label_14 = QtWidgets.QLabel(self.tab_4)
        self.label_14.setGeometry(QtCore.QRect(10, 130, 121, 41))
        self.label_14.setObjectName("label_14")
        self.num_disp = QtWidgets.QLineEdit(self.tab_4)
        self.num_disp.setGeometry(QtCore.QRect(150, 130, 61, 23))
        self.num_disp.setObjectName("num_disp")
        self.label_15 = QtWidgets.QLabel(self.tab_4)
        self.label_15.setGeometry(QtCore.QRect(10, 180, 151, 31))
        self.label_15.setObjectName("label_15")
        self.uniquenessRatio = QtWidgets.QLineEdit(self.tab_4)
        self.uniquenessRatio.setGeometry(QtCore.QRect(150, 180, 61, 23))
        self.uniquenessRatio.setObjectName("uniquenessRatio")
        self.label_16 = QtWidgets.QLabel(self.tab_4)
        self.label_16.setGeometry(QtCore.QRect(10, 220, 121, 31))
        self.label_16.setObjectName("label_16")
        self.speckleWindowSize = QtWidgets.QLineEdit(self.tab_4)
        self.speckleWindowSize.setGeometry(QtCore.QRect(150, 220, 61, 23))
        self.speckleWindowSize.setObjectName("speckleWindowSize")
        self.label_18 = QtWidgets.QLabel(self.tab_4)
        self.label_18.setGeometry(QtCore.QRect(230, 50, 121, 21))
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.tab_4)
        self.label_19.setGeometry(QtCore.QRect(230, 90, 121, 21))
        self.label_19.setObjectName("label_19")
        self.disp12MaxDiff = QtWidgets.QLineEdit(self.tab_4)
        self.disp12MaxDiff.setGeometry(QtCore.QRect(360, 90, 71, 23))
        self.disp12MaxDiff.setObjectName("disp12MaxDiff")
        self.speckleRange = QtWidgets.QLineEdit(self.tab_4)
        self.speckleRange.setGeometry(QtCore.QRect(360, 50, 71, 23))
        self.speckleRange.setObjectName("speckleRange")
        self.label_20 = QtWidgets.QLabel(self.tab_4)
        self.label_20.setGeometry(QtCore.QRect(270, 130, 121, 21))
        self.label_20.setObjectName("label_20")
        self.lmbda = QtWidgets.QLineEdit(self.tab_4)
        self.lmbda.setGeometry(QtCore.QRect(360, 150, 71, 23))
        self.lmbda.setObjectName("lmbda")
        self.label_21 = QtWidgets.QLabel(self.tab_4)
        self.label_21.setGeometry(QtCore.QRect(230, 150, 121, 21))
        self.label_21.setObjectName("label_21")
        self.sigma = QtWidgets.QLineEdit(self.tab_4)
        self.sigma.setGeometry(QtCore.QRect(360, 180, 71, 23))
        self.sigma.setObjectName("sigma")
        self.label_22 = QtWidgets.QLabel(self.tab_4)
        self.label_22.setGeometry(QtCore.QRect(230, 180, 121, 21))
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.tab_4)
        self.label_23.setGeometry(QtCore.QRect(230, 220, 121, 21))
        self.label_23.setObjectName("label_23")
        self.visual_multiplier = QtWidgets.QLineEdit(self.tab_4)
        self.visual_multiplier.setGeometry(QtCore.QRect(360, 220, 71, 23))
        self.visual_multiplier.setObjectName("visual_multiplier")
        self.tabWidget_2.addTab(self.tab_4, "")
        self.label_17 = QtWidgets.QLabel(self.Calibrate_System)
        self.label_17.setGeometry(QtCore.QRect(20, 260, 81, 16))
        self.label_17.setObjectName("label_17")
        self.chess_size_x = QtWidgets.QSpinBox(self.Calibrate_System)
        self.chess_size_x.setGeometry(QtCore.QRect(130, 260, 47, 24))
        self.chess_size_x.setMinimum(1)
        self.chess_size_x.setProperty("value", 9)
        self.chess_size_x.setObjectName("chess_size_x")
        self.chess_size_y = QtWidgets.QSpinBox(self.Calibrate_System)
        self.chess_size_y.setGeometry(QtCore.QRect(190, 260, 47, 24))
        self.chess_size_y.setMinimum(1)
        self.chess_size_y.setProperty("value", 6)
        self.chess_size_y.setObjectName("chess_size_y")
        self.label_24 = QtWidgets.QLabel(self.Calibrate_System)
        self.label_24.setGeometry(QtCore.QRect(180, 260, 21, 16))
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.Calibrate_System)
        self.label_25.setGeometry(QtCore.QRect(20, 300, 141, 31))
        self.label_25.setObjectName("label_25")
        self.chess_square_side = QtWidgets.QLineEdit(self.Calibrate_System)
        self.chess_square_side.setEnabled(True)
        self.chess_square_side.setGeometry(QtCore.QRect(190, 310, 71, 21))
        self.chess_square_side.setObjectName("chess_square_side")
        self.progressBar_Calibrate = QtWidgets.QProgressBar(self.Calibrate_System)
        self.progressBar_Calibrate.setGeometry(QtCore.QRect(390, 570, 311, 31))
        self.progressBar_Calibrate.setProperty("value", 0)
        self.progressBar_Calibrate.setTextVisible(True)
        self.progressBar_Calibrate.setObjectName("progressBar_Calibrate")
        self.log_text = QtWidgets.QPlainTextEdit(self.Calibrate_System)
        self.log_text.setGeometry(QtCore.QRect(60, 400, 691, 151))
        self.log_text.setReadOnly(True)
        self.log_text.setObjectName("log_text")
        self.start_calibration = QtWidgets.QPushButton(self.Calibrate_System)
        self.start_calibration.setGeometry(QtCore.QRect(110, 570, 181, 41))
        self.start_calibration.setAutoFillBackground(False)
        self.start_calibration.setObjectName("start_calibration")
        self.label_29 = QtWidgets.QLabel(self.Calibrate_System)
        self.label_29.setGeometry(QtCore.QRect(20, 360, 141, 31))
        self.label_29.setObjectName("label_29")
        self.cam_L_idx = QtWidgets.QSpinBox(self.Calibrate_System)
        self.cam_L_idx.setGeometry(QtCore.QRect(190, 360, 47, 24))
        self.cam_L_idx.setMinimum(0)
        self.cam_L_idx.setProperty("value", 2)
        self.cam_L_idx.setObjectName("cam_L_idx")
        self.label_30 = QtWidgets.QLabel(self.Calibrate_System)
        self.label_30.setGeometry(QtCore.QRect(160, 360, 41, 31))
        self.label_30.setObjectName("label_30")
        self.cam_R_idx = QtWidgets.QSpinBox(self.Calibrate_System)
        self.cam_R_idx.setGeometry(QtCore.QRect(320, 360, 47, 24))
        self.cam_R_idx.setMinimum(0)
        self.cam_R_idx.setProperty("value", 1)
        self.cam_R_idx.setObjectName("cam_R_idx")
        self.label_31 = QtWidgets.QLabel(self.Calibrate_System)
        self.label_31.setGeometry(QtCore.QRect(280, 360, 41, 31))
        self.label_31.setObjectName("label_31")
        self.tabWidget.addTab(self.Calibrate_System, "")
        self.Import_Calibrated_Parameters = QtWidgets.QWidget()
        self.Import_Calibrated_Parameters.setObjectName("Import_Calibrated_Parameters")
        self.tabWidget.addTab(self.Import_Calibrated_Parameters, "")
        self.Generate_Depth_Maps = QtWidgets.QWidget()
        self.Generate_Depth_Maps.setObjectName("Generate_Depth_Maps")
        self.tabWidget.addTab(self.Generate_Depth_Maps, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 812, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Depth Map Generator using Stero Imaging"))
        self.label.setText(_translate("MainWindow", "Working Directory:"))
        self.label_2.setText(_translate("MainWindow", "Number of Photos\n"
"to take in Calibration:"))
        self.label_3.setText(_translate("MainWindow", "Number of Photos \n"
"to take for Test:"))
        self.label_4.setText(_translate("MainWindow", "Take all the correct\n"
"images or allow choosing?"))
        self.allow_choosing.setText(_translate("MainWindow", "Allow Choosing"))
        self.radioButton_2.setText(_translate("MainWindow", "Take All"))
        self.label_5.setText(_translate("MainWindow", "If All Taken,\n"
"timing (ms) of \n"
"previsualization"))
        self.previs_ms.setText(_translate("MainWindow", "4000"))
        self.label_6.setText(_translate("MainWindow", "Calibrate \n"
"Each Camera"))
        self.camera_criteria_eps.setText(_translate("MainWindow", "1e-5"))
        self.camera_criteria_its.setText(_translate("MainWindow", "1000"))
        self.stereocalib_criteria_eps.setText(_translate("MainWindow", "1e-5"))
        self.stereocalib_criteria_its.setText(_translate("MainWindow", "1000"))
        self.label_9.setText(_translate("MainWindow", "Stereo \n"
"Calibration:"))
        self.label_26.setText(_translate("MainWindow", "Chess\n"
"Corner\n"
"Detection:"))
        self.corner_criteria_its.setText(_translate("MainWindow", "1000"))
        self.corner_criteria_eps.setText(_translate("MainWindow", "1e-5"))
        self.label_27.setText(_translate("MainWindow", "Max. Iterations"))
        self.label_28.setText(_translate("MainWindow", "Epsilon"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab), _translate("MainWindow", "Opt. Stop Crit."))
        self.CALIB_FIX_INTRINSIC.setText(_translate("MainWindow", "CALIB_FIX_INTRINSIC"))
        self.CALIB_FIX_PRINCIPAL_POINT.setText(_translate("MainWindow", "CALIB_FIX_PRINCIPAL_POINT"))
        self.CALIB_FIX_FOCAL_LENGTH.setText(_translate("MainWindow", "CALIB_FIX_FOCAL_LENGTH"))
        self.CALIB_SAME_FOCAL_LENGTH.setText(_translate("MainWindow", "CALIB_SAME_FOCAL_LENGTH"))
        self.CALIB_ZERO_TANGENT_DIST.setText(_translate("MainWindow", "CALIB_ZERO_TANGENT_DIST"))
        self.CALIB_FIX_ASPECT_RATIO.setText(_translate("MainWindow", "CALIB_FIX_ASPECT_RATIO"))
        self.CALIB_FIX_K5.setText(_translate("MainWindow", "CALIB_FIX_K5"))
        self.CALIB_FIX_K2.setText(_translate("MainWindow", "CALIB_FIX_K2"))
        self.CALIB_FIX_K3.setText(_translate("MainWindow", "CALIB_FIX_K3"))
        self.CALIB_FIX_K4.setText(_translate("MainWindow", "CALIB_FIX_K4"))
        self.CALIB_FIX_K1.setText(_translate("MainWindow", "CALIB_FIX_K1"))
        self.CALIB_FIX_K6.setText(_translate("MainWindow", "CALIB_FIX_K6"))
        self.CALIB_USE_INTRINSIC_GUESS.setText(_translate("MainWindow", "CALIB_USE_INTRINSIC_GUESS"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_2), _translate("MainWindow", "StereoCalibrate"))
        self.CALIB_ZERO_DISPARITY.setText(_translate("MainWindow", "CALIB_ZERO_DISPARITY"))
        self.label_10.setText(_translate("MainWindow", "Alpha:"))
        self.alpha.setText(_translate("MainWindow", "0.9"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), _translate("MainWindow", "StereoRectify"))
        self.block_size.setText(_translate("MainWindow", "11"))
        self.label_11.setText(_translate("MainWindow", "Block Size (3-11):"))
        self.label_12.setText(_translate("MainWindow", "Min Disparity:"))
        self.min_disp.setText(_translate("MainWindow", "-1"))
        self.label_13.setText(_translate("MainWindow", "Max Disparity:"))
        self.max_disp.setText(_translate("MainWindow", "63"))
        self.label_14.setText(_translate("MainWindow", "Num Disparities:\n"
"(max-min should \n"
"be divsble by 16)"))
        self.num_disp.setText(_translate("MainWindow", "0.9"))
        self.label_15.setText(_translate("MainWindow", "Uniqueness Ratio \n"
"(5-15):"))
        self.uniquenessRatio.setText(_translate("MainWindow", "10"))
        self.label_16.setText(_translate("MainWindow", "Speckle Window\n"
" Size (50-200):"))
        self.speckleWindowSize.setText(_translate("MainWindow", "200"))
        self.label_18.setText(_translate("MainWindow", "Speckle Range (1-2):"))
        self.label_19.setText(_translate("MainWindow", "Disp12MaxDiff:"))
        self.disp12MaxDiff.setText(_translate("MainWindow", "0"))
        self.speckleRange.setText(_translate("MainWindow", "2"))
        self.label_20.setText(_translate("MainWindow", "FILTER parameters:"))
        self.lmbda.setText(_translate("MainWindow", "8000"))
        self.label_21.setText(_translate("MainWindow", "Lambda:"))
        self.sigma.setText(_translate("MainWindow", "1.3"))
        self.label_22.setText(_translate("MainWindow", "Sigma:"))
        self.label_23.setText(_translate("MainWindow", "Visual Multiplier:"))
        self.visual_multiplier.setText(_translate("MainWindow", "6"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), _translate("MainWindow", "Disparity SGBM"))
        self.label_17.setText(_translate("MainWindow", "Chess size:"))
        self.label_24.setText(_translate("MainWindow", "x"))
        self.label_25.setText(_translate("MainWindow", "Chess square side\n"
" (you will fix the units):"))
        self.chess_square_side.setText(_translate("MainWindow", "2.4"))
        self.log_text.setPlainText(_translate("MainWindow", "Click Start Calibration to begin calibration process...\n"
""))
        self.start_calibration.setText(_translate("MainWindow", "START CALIBRATION"))
        self.label_29.setText(_translate("MainWindow", "Camera Indices:"))
        self.label_30.setText(_translate("MainWindow", "Left:"))
        self.label_31.setText(_translate("MainWindow", "Right:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Calibrate_System), _translate("MainWindow", "Calibrate System"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Import_Calibrated_Parameters), _translate("MainWindow", "Import Calibrated Parameters"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Generate_Depth_Maps), _translate("MainWindow", "Generate Depth Maps"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
